### ISSUE TITLE
Combine dependent/conflicting Work Items

### ISSUE THREAD

**Issue by ferovar** [forcedotcom/devops-center-feedback#137] opened 2022-03-15 15:55 UTC
We always deploy changes from our dev environment up to a QA or Staging environment for a QA team/business to verify it works as expected. Often times, testing may fail or a requirement was missed so we need to bring it back to dev for more changes.

Within DevOps Center, I am not seeing how this is supported. Once it reaches "Promoted" status, I cannot "move it back" to dev for more work to be done. The stages along the top seem to be display only and I cannot find any buttons/links to move it back to dev.

Is there another way to accomplish what I am looking for?

**Comment by martinlezer** [comment] 2022-11-14 08:53
Hello @ekapner ,

I used the workaround a lot and it sometimes results in deployment problems due to conflicts.

**Comment by SAxcell** [comment] 2022-12-05 19:27
For exactly the reasons outlined in the initial request, this would be a huge help to us.  Users aren't always very good at detailing all of the requirements.  Often they miss things, or add things along the way as they're testing.  Having an incomplete WI in the pipeline interferes with other projects being promoted successfully.

**Comment by kfidelak94** [comment] 2023-01-23 01:06
We're prioritizing this feature.  Stay tuned for more details on the proposed solution here shortly.

**Comment by GilsonCanario** [comment] 2023-03-22 01:21
Hi @RupertBarrow - Yes, we interviewed some users to understand their pain points and different use cases, and subsequently developed a prototype to address the issues they raised. We tested the prototype with a sample of users and received positive feedback, which confirmed the potential usefulness of our solution. We discovered that the actual root cause is the inability of users to promote fixes further in the pipeline due to conflicts and dependencies that arise when creating new work items to address issues from previously promoted one. To address this, we will be introducing an enhancement that includes an option to “Combine work items into a single work item” when a promotion is blocked due to a dependency or a potential conflict is detected. This new feature will help prevent situations where changes cannot be promoted further due to merge conflicts or dependencies.

**Comment by lramosmtx** [comment] 2023-04-03 20:04
The combination of multiple workitems should be done at any steps or stages of the pipeline.
Like the initial demand, in my case.

Our business analyst develop a Flow then he promote to the next stage that it is our UAT (Full Sandbox). The business is not ok with the WI we cannot unpromote the WI. We need to create another WorkItem for people that are not technical they don't understand the mainset.

When we create the new WI, we probably select the old one or the old branch maybe could be a solution also and it is more usefull for the non technical members.

**Comment by iaroraSignify** [comment] 2023-07-25 14:45
Is there any update on this issue? When can we expect to have this fix where we can move the work item to dev again after having the status promoted?

**Comment by KarelBONSAISkills** [comment] 2023-09-22 14:05
Not sure if this is still an actively read thread but I have been checking it from time to time over the past 18 months and I can't believe no advancement has been made on this critical functionality/request. Anyone know about any scheduled progress on this?

**Comment by RupertBarrow** [comment] 2023-09-23 08:23
Hi @KarelBONSAISkills , just above your comment it says that this was shipped by @GilsonCanario 3 weeks ago ...

**Comment by KarelBONSAISkills** [comment] 2023-09-25 09:03
@RupertBarrow - Thank you for pointing that out, I was too quick on the keys. Looking forward to this since this was the only thing standing in the way of actually using DevOps center at all our clients.

**Comment by sly-zeplug** [comment] 2023-11-03 18:26
Just tried it ! It work well

**Closed** 2024-02-08 16:19 UTC
Labels: Revert/rollback/fix
